---
'''apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  selector:
    matchLabels:
      app: backend
      dash.ulagbulag.io/subject: mobilex-exp
  template:
    metadata:
      labels:
        app: backend
        dash.ulagbulag.io/subject: mobilex-exp
    spec:
      containers:
        - name: server
          # TODO(user): change to your image
          image: docker.io/jaein12/mobilex-project-backend:v4.0
          env:
            - name: BASE_URL
              value: /api/v1
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: OPENAI_API_KEY
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Secret
metadata:
  name: openai
stringData:
  # TODO(user): change your own token!
  OPENAI_API_KEY:''' #There is an api key in the authentic code, but for the github, we could not put the api key because of the error.